import * as React from "react";
export class WarscrollCard extends React.Component {
    render() {
        const { warscroll } = this.props;
        return (React.createElement("section", null,
            React.createElement("div", null,
                React.createElement("div", { className: "img", style: { backgroundImage: `url("/images/models/${warscroll.name}.jpeg")` } }),
                React.createElement("div", { className: "aos-profile" },
                    React.createElement("div", { style: { top: 'calc(41% - 24px)', left: '0', bottom: '0', right: '0' } }, warscroll.move),
                    React.createElement("div", { style: { top: 'calc(41%)', left: '-52px', bottom: '0', right: '0' } }, warscroll.wounds),
                    React.createElement("div", { style: { top: 'calc(41%)', left: '52px', bottom: '0', right: '0' } }, warscroll.save),
                    React.createElement("div", { style: { top: 'calc(41% + 27px)', left: '0', bottom: '0', right: '0' } }, warscroll.bravery)),
                React.createElement("p", { className: "header" },
                    React.createElement("h3", { className: "name" }, warscroll.name),
                    React.createElement("p", { className: "flavor" }, warscroll.flavorText),
                    React.createElement("p", { className: "description" }, warscroll.description))),
            React.createElement("table", null,
                React.createElement("thead", null,
                    React.createElement("tr", null,
                        React.createElement("td", null, "Melee Weapons"),
                        React.createElement("td", null, "Rng"),
                        React.createElement("td", null, "Att"),
                        React.createElement("td", null, "Hit"),
                        React.createElement("td", null, "Wnd"),
                        React.createElement("td", null, "Rend"),
                        React.createElement("td", null, "Dmg"))),
                React.createElement("tbody", null, warscroll.meleeWeapons.map((weapon) => {
                    return (React.createElement("tr", null,
                        React.createElement("td", null, weapon.name),
                        React.createElement("td", null, weapon.range),
                        React.createElement("td", null, weapon.attacks),
                        React.createElement("td", null, weapon.toHit),
                        React.createElement("td", null, weapon.toWound),
                        React.createElement("td", null, weapon.rend),
                        React.createElement("td", null, weapon.damage)));
                }))),
            React.createElement("div", { style: { height: "14px" } }),
            React.createElement("table", null,
                React.createElement("thead", null,
                    React.createElement("tr", null,
                        React.createElement("td", null, "Missle Weapons"),
                        React.createElement("td", null, "Rng"),
                        React.createElement("td", null, "Att"),
                        React.createElement("td", null, "Hit"),
                        React.createElement("td", null, "Wnd"),
                        React.createElement("td", null, "Rend"),
                        React.createElement("td", null, "Dmg"))),
                React.createElement("tbody", null, warscroll.missleWeapons.map((weapon) => {
                    return (React.createElement("tr", null,
                        React.createElement("td", null, weapon.name),
                        React.createElement("td", null, weapon.range),
                        React.createElement("td", null, weapon.attacks),
                        React.createElement("td", null, weapon.toHit),
                        React.createElement("td", null, weapon.toWound),
                        React.createElement("td", null, weapon.rend),
                        React.createElement("td", null, weapon.damage)));
                }))),
            React.createElement("div", { style: { height: '500px' } })));
    }
}
